
# Colores generales

COLOR_FONDO_VENTANA = "#6C78D3"
COLOR_PANEL_IZQUIERDO = "#4E5999"
COLOR_PANEL_DERECHO = "#616DB3"

COLOR_TEXTO_CLARO = "#F8F9FA"
COLOR_TEXTO_OSCURO = "#1B1F23"

COLOR_TITULO = "#FFFFFF"
COLOR_SUBTITULO = "#D6E4F0"

COLOR_BOTON_PRIMARIO = "#5DADE2"
COLOR_BOTON_PRIMARIO_HOVER = "#E7E7E7"

COLOR_BOTON_LIMPIAR = "#F5B041"
COLOR_BOTON_LIMPIAR_HOVER = "#E7E7E7"

COLOR_CAJA_TEXTO = "#FFFFFF"
COLOR_BORDE_CAJA = "#050505"

COLOR_SLIDER_FONDO = "#000000"
COLOR_SLIDER_BARRA = "#4F83B8"
COLOR_SLIDER_ACTIVO = "#5DADE2"


# Fuentes

FUENTE_TITULO = ("Arial", 16, "bold")
FUENTE_SUBTITULO = ("Arial", 12, "bold")
FUENTE_NORMAL = ("Arial", 11)
FUENTE_PEQUENA = ("Arial", 10)


# Medidas

PADDING_GENERAL_X = 12
PADDING_GENERAL_Y = 10

ANCHO_BOTON = 18
ALTO_BOTON = 1